### PR TITLE
New content info

### PR DESCRIPTION
**Pull request by k3ii**
docs(info): add how to become speaker

### CODE REVIEW

**Comment by MrSunshyne** [comment]
@k3ii the build is failing because the .md files were moved from /content to /content/info

In the menu there's a link to /history, which is no longer valid because the files were moved. I suggest trying to move them back to /content. Might fix this

**Comment by k3ii** [comment]
@MrSunshyne  it is still failing. It cannot find `how-to-become-a-speaker.md` and `how-to-contribute.md`.
Do you know what is missing?

**Comment by MrSunshyne** [comment]
@k3ii checks are passing! 
The way nuxt generate works, it crawls all the links on our pages and explores all other links and generates their html files.

Since we have not linked to `/how-to-contribute` anywhere on the website, this will be skipped and not be part of the final bundle. This is why it wasn't generated.

You can make it discoverable by adding it to the menu like we did for the history page.
Bear in my that since this page will now be explored by the compiler, nuxt will try to find every other relative link within this file and pre-render them as well. If there are broken links, it will fail the build. 

You can test this locally by running `pnpm nuxt generate`

I suggest naming the file /contribute instead of /how-to-contribute

**Comment by k3ii** [comment]
I get this error with nuxt generate:


```
> ls
README.md            content              public
app.config.ts        eslint.config.mjs    server
app.vue              layouts              store
assets               lib                  styles
auth-utils           nuxt.config.ts       tailwind.config.js
components           package.json         tests
components.json      pages                tsconfig.json
composables          playwright.config.ts utils
> pnpm nuxt generate
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "nuxt" not found
```

 Also, I added `contribute` to Menu and it's failing.

**Comment by k3ii** [comment]
I'm so bad at being a frontend dev xD

**Comment by MrSunshyne** [comment]
@k3ii  you can run `pnpm nuxt generate` in the root of the repo, it will run the command in the nuxt package.

i see you're already in the folder, if so, you can simply run `pnpm generate` and it should be fine! 
of course, you should run `pnpm install` at least once before trying to generate. That's in the docs :P

**Review by MrSunshyne — COMMENTED** [review]
the pages look good! i will modify the content in another PR

**Pull request merged**
