### PR TITLE
Add cz-git to standard git commit msg

### PR DESCRIPTION
**Pull request by derecklhw**
## How to use ?

Run `pnpm commit` in root of project

Documentation: https://cz-git.qbb.sh/

## Screenshots

image

image

### CODE REVIEW

**Comment by k3ii** [comment]
@derecklhw  can it be run via `git cz` ?

**Comment by derecklhw** [comment]
[git-cz](https://github.com/streamich/git-cz) is only a semantic used by `cz-git`

**Comment by MrSunshyne** [comment]
Interesting! Will test in a moment 

🫡

**Comment by MrSunshyne** [comment]
thanks @derecklhw !
looks nice, but shouldn't be enforced, should be a suggestion to contributors

I dont see myself using it for every commit :D 
but after using a few times, i think i can already type it myself, so it's a great way to learn conventional commits

**Pull request merged**
